-
-----------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels: 
    apps: jenk
spec:
  replicas: 
  selector:
    matchLabels:
      app: jenk
  template:
    metadata:
      labels:
        app: jenk
    spec:
      containers:
        - name: jenks
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenk-vol
              mountPath: /var/jenkins
      volumes:
        - name: jenk-vol
          emptyDir: {}

---------

apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector: 
    app: jenk
  type: LoadBalancer
  ports:
    - name: jenkins-svc
      port: 8080
      targetPort: 9376
